// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDug8n-F_3bM8YRgavyYlfad_ljUz91oHc',
    appId: '1:215692238547:web:5611aad3526be71852fe26',
    messagingSenderId: '215692238547',
    projectId: 'daloy-661ce',
    authDomain: 'daloy-661ce.firebaseapp.com',
    storageBucket: 'daloy-661ce.firebasestorage.app',
    measurementId: 'G-7TRYMKHDNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44l6mP2AMP4CcWPvEBWNyJbGew72-kRc',
    appId: '1:215692238547:android:1f7be298cdcf551c52fe26',
    messagingSenderId: '215692238547',
    projectId: 'daloy-661ce',
    storageBucket: 'daloy-661ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfe5bkzjBzwnLaO0LOz7hBhJeQL4Ko3n0',
    appId: '1:215692238547:ios:96231a28ff76a50852fe26',
    messagingSenderId: '215692238547',
    projectId: 'daloy-661ce',
    storageBucket: 'daloy-661ce.firebasestorage.app',
    iosBundleId: 'com.example.idoxsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfe5bkzjBzwnLaO0LOz7hBhJeQL4Ko3n0',
    appId: '1:215692238547:ios:96231a28ff76a50852fe26',
    messagingSenderId: '215692238547',
    projectId: 'daloy-661ce',
    storageBucket: 'daloy-661ce.firebasestorage.app',
    iosBundleId: 'com.example.idoxsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDug8n-F_3bM8YRgavyYlfad_ljUz91oHc',
    appId: '1:215692238547:web:140303d1364cd03252fe26',
    messagingSenderId: '215692238547',
    projectId: 'daloy-661ce',
    authDomain: 'daloy-661ce.firebaseapp.com',
    storageBucket: 'daloy-661ce.firebasestorage.app',
    measurementId: 'G-ZRRXY4QLJY',
  );
}